// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlVUxpOo9-OZYVbD8aYGR0rsZE7OCBI1M',
    appId: '1:425387400471:web:58f56feaa3d6807621eb52',
    messagingSenderId: '425387400471',
    projectId: 'saglik-takip-asistani',
    authDomain: 'saglik-takip-asistani.firebaseapp.com',
    storageBucket: 'saglik-takip-asistani.appspot.com',
    measurementId: 'G-7229TV58ZD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDStHKBN2eV59HCmWLM1WPg8rvikMKdTVo',
    appId: '1:425387400471:android:b7f494ecca4cbedc21eb52',
    messagingSenderId: '425387400471',
    projectId: 'saglik-takip-asistani',
    storageBucket: 'saglik-takip-asistani.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCV7kogJkzZDMc6PIOmmh0M99tkYwYyeMk',
    appId: '1:425387400471:ios:a2222e2c7e6962ae21eb52',
    messagingSenderId: '425387400471',
    projectId: 'saglik-takip-asistani',
    storageBucket: 'saglik-takip-asistani.appspot.com',
    iosBundleId: 'com.example.saglikasistani',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCV7kogJkzZDMc6PIOmmh0M99tkYwYyeMk',
    appId: '1:425387400471:ios:19dbadc8d61cdd5021eb52',
    messagingSenderId: '425387400471',
    projectId: 'saglik-takip-asistani',
    storageBucket: 'saglik-takip-asistani.appspot.com',
    iosBundleId: 'com.example.saglikasistani.RunnerTests',
  );
}
